spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_prod
    username: sfg_prod_user
    password: 123456
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false
    properties:
      javax:
        persistance:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: guru_database_create.sql